name: poky-container build and test
on:
  push:
  pull_request:

  # Allow for manually running
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      BASE_DISTRO: ubuntu-20.04
      REPO: tlangohr/yoctodev
      DEFAULT_DISTRO: ubuntu-20.04
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      # Build and test the images
      - name: Run build.sh
        run: ./build.sh

      # Deploy the images
      - name: Deploy
        run: bash deploy.sh
